debug = true

logLevel = "ERROR"
defaultEntryPoints = ["http","https"]

[entryPoints]
  [entryPoints.http]
    address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
    address = ":443"
    [entryPoints.https.tls]

[retry]

[docker]
  endpoint = "unix:///var/run/docker.sock"
  watch = true
  exposedbydefault = true

[web]
  address = ":8080"
  readOnly = true

[web.auth.basic]
  users = ["admin:$apr1$1eSdhvvq$Uaax6mF9yhynNCIMEm8k71"] #Htpasswd Generator -> admin:admin

[acme]
  email = "your@email.com"
  storageFile = "acme.json"
  entryPoint = "https"
  #onHostRule = true
  onDemand = true

[acme.httpChallenge]
  entryPoint = "http"

[[acme.domains]]
  main = "mind7.fr"
  sans = ["traefik.mind7.tk", "someapps.mind7.fr"]

[[acme.domains]]
  main = "gitlab.mind7.fr"
