version: '3'

services:
 git:
  image: 'gitlab/gitlab-ce:latest'
  restart: always
  networks:
    - proxy
    - gitlab
  hostname: 'gitlab.mind7.fr'
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'https://gitlab.mind7.fr'
      nginx['listen_port'] = 443
      nginx['listen_https'] = false
      nginx['proxy_set_headers'] = {
        'X-Forwarded-Proto' => 'https',
        'X-Forwarded-Ssl' => 'on',
        'Host' => 'gitlab.mind7.fr'
      }
  ports:
    - '22:22'
  volumes:
    - '/srv/gitlab/config:/etc/gitlab'
    - '/srv/gitlab/logs:/var/log/gitlab'
    - '/srv/gitlab/data:/var/opt/gitlab'
  labels:
    - "traefik.backend=gitlab.mind7.fr"
    - "traefik.frontend.rule=Host:gitlab.mind7.fr"
    - "traefik.port=443"
    - "traefik.docker.network=proxy"
    - "traefik.frontend.entryPoints=https,http"
   # - "traefik.frontend.headers.SSLRedirect=true"

networks:
  proxy:
    external: true
  gitlab:
    external: false
